### PR TITLE
Enabled custom sounds for the Boeing b737-800 too.

### PR DESCRIPTION
**Pull request by kolos26**
I have enabled the GeoFs-737-Immersion-SFX addon for the b737-800 (only the spice9 version).
I have also fixed a bug that throws an error when I change to the compatible aircraft for the second time in one game. (The modified version can be found here [https://github.com/kolos26/GeoFs-737-Immersion-SFX-for-Realism-Addon](https://github.com/kolos26/GeoFs-737-Immersion-SFX-for-Realism-Addon) )

Thanks for this well made addon, I hope my new functions will be useful.
Best regards,
Kolos

### CODE REVIEW

**Comment by NVB9ALT** [comment]
two questions.
- I've tried this before with the 737 MAX 8 and had to remove several functions to avoid loads of console errors when in a 737 MAX. Does your code have the same problem?
- Could you remove the camera shake code? it conflicts with my stall buffet.
If your code runs with no console errors while switching to and from the subject aircraft (737-700, 737-800, 737 MAX 8), and you remove the camera shake functions, then I'll be very happy to implement it.

**Comment by kolos26** [comment]
I have removed the shake effect. I have not implemented MAX because it has very different sound. If you don't think it's a problem, I can try to add that too.

**Comment by NVB9ALT** [comment]
Alright, I'll switch to your script and test it when I get home from school.

**Comment by NVB9ALT** [comment]
Just updated the Realism Pack, want to test it before I have a chance to?

**Comment by kolos26** [comment]
you need to merge the main.js too. This script only contains changes to be able to reload it. The 738 is in the main.js

**Comment by NVB9ALT** [comment]
Latest commit features a more concise version of your method

**Comment by NVB9ALT** [comment]
Problem - sounds broken for 737 and 737-800. Function error at line 1105 but that line is empty in your code.

**Pull request closed without merging**
