### PR TITLE
Fixed a320neo and b737 sound error

### PR DESCRIPTION
**Pull request by kolos26**
Dear Julian,

I have fixed the bug, that caused the problem. Please let me know, if I can do anything to improve your project.

Kind regards,
Kolos

### CODE REVIEW

**Comment by NVB9ALT** [comment]
Will try it later; it has to trickle from GitHub through GitHack to the end user, which takes a little bit.

**Comment by kolos26** [comment]
The fix is not in the githack addon. I modified the a320 function in the code, so you need to merge that part. Have a nice day!

**Comment by NVB9ALT** [comment]
The problem still exists - when first loading either 737, the alarms and the different sounds based on camera position don't work, and then switching to a 737-800 causes the sounds to vanish. Same thing happens the other way.

**Comment by kolos26** [comment]
The first load works for me without any problem. The changing between the same types will be fixed of course.

**Pull request closed without merging**
